#!/bin/bash

# Set the source and destination devices
src_dev="/dev/sda"
dest_devs=( "/dev/sdb" "/dev/sdc" ) # add more devices here if needed

# Create a partition table on the destination devices
for dev in "${dest_devs[@]}"
do
  sudo parted -s $dev mklabel gpt
done

# Clone the source device to the destination devices
for dev in "${dest_devs[@]}"
do
  sudo dd if=$src_dev of=$dev bs=1M status=progress
done

# Update the UUID of the cloned partitions
for dev in "${dest_devs[@]}"
do
  sudo blkid -o export $dev | grep '^UUID' | while read uuid; do
    sudo sed -i "s/${src_dev##*/}-[0-9]*/${dev##*/}-$(basename $uuid)/g" /etc/fstab
  done
done

# Update the GRUB configuration to include the cloned devices
for dev in "${dest_devs[@]}"
do
  sudo update-grub
done

# Install GRUB on the cloned devices
for dev in "${dest_devs[@]}"
do
  sudo grub-install $dev
done
