#!/bin/bash
echo "STRESS GPU ALL "

docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn
docker run --rm --gpus all gpu_burn